export enum EventStatus {
    APERTURADO = "APERTURADO",
    EN_CURSO = "EN_CURSO",
    CLAUSURADO = "CLAUSURADO",
    CANCELADO = "CANCELADO"
}

export enum EventType {
    CONFERENCIA = "CONFERENCIA",
    TALLER = "TALLER",
    EXPOSICION = "EXPOSICION",
    CONCIERTO = "CONCIERTO",
    OBRA_DE_TEATRO = "OBRA_DE_TEATRO",
    PROYECCION = "PROYECCION",
    FERIA = "FERIA",
    OTRO = "OTRO"
}